# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true
target 'webkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JKWKWebViewHandler', :path => '../'
  # Pods for webkit
   # pod "JKWKWebViewHandler"
  target 'webkitTests' do
    inherit! :search_paths
    # Pods for testing
	
  end

  target 'webkitUITests' do
    # Pods for testing
  end

end
